import Header from '@/component/Header';
import './globals.css';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/component/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next Blog - Home Page',
  description: 'Generated by create next app with typescript - nex-blog',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="container">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
