import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Blog - Home Page',
  description: 'Generated by create next app with typescript - nex-blog',
};

export default function Home() {
  return (
    <div>
      <h1>Home Page</h1>
    </div>
  );
}
